# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SP-ipt-erfa-jvl'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr create --resource-group ipt-we-erfa-2-rg --name JVLContainerRegistry --sku Basic
